### PR TITLE
(#53) Pager Visibility for less than results

### LINKED ISSUE #53: Pager Should Not Appear if ≤ 20 Results (can resolve post launch)
**Note:** This issue is not a deal breaker for launch

### Issue description
If there are 20 or less search results, the pager should not appear since there are no additional pages for the user to toggle through. This is the case with CTS results. But SWS shows the pager (http://ncigovcdode377.prod.acquia-sites.com/search/results?swKeyword=mynci)

> **ESTIMATE**

### Steps to reproduce the issue

1.  On CGov, search `mynci`
2. You should get less than 20 results back (currently 8 results)  
3. Top and bottom pager appears on search results page, showing only 1 page

### What's the expected result?
- No pager should appear (see CTS example with only a few results - no pager appears: https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=2&stg=C8815&t=C3158)

### What's the actual result?
- Top and bottom pager appears on search results page, showing only 1 page

### Additional details / screenshot
image (1)

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #53 

* When there are less results than max view by on page - hide the pager
https://react-app-dev.cancer.gov/sitewide-search-app/pr-70?cfg=0&swkeyword=mynci

### CODE REVIEW

File: src/components/molecules/search-results-list/search-results-list.jsx [hunk 1]
```diff
@@ -93,14 +95,16 @@ const SearchResultsList = ({
...
 				</h4>
-				<SearchResultsPager
-					testid={testIds.RESULTS_PAGER_TOP}
-					current={currentPage}
-					totalResults={results.totalResults}
-					resultsPerPage={resultsPerPage}
-					language={language}
-					keyword={keyword}
-				/>
+				{!hidePage && (
```
Comment (seyilonge-nci) [inline src/components/molecules/search-results-list/search-results-list.jsx:98]: Can you use `showPage` instead and that shows the pager only when true.

Comment (karlikpj) [reply src/components/molecules/search-results-list/search-results-list.jsx:98]: So this is the issue - we can't cause best bets and dictionary fails tests cause of async somewhere..

**Comment by lburack** [comment]
Looks good on browsers on my Mac. Passes UX Review!
