### PR TITLE
(#89) make pager consistent

### LINKED ISSUE #89: Pager on the Search Results page is not consistent with other pagers on the site
### Issue description
*Description of the issue*

When we click the last page in the pager of CTS search results page and the SWS results page, the number of page link displayed in the pager (number of pages listed within the pager) in the CTS search results page and SWS results page is not same.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to ODE 377 and perform search with "cancer" 
2. Click the page link "1517" (or the last page that you see ) in the pager.
3. Repeat step 1 and perform default search (without applying any filter) on CTS Basic search form
4. Click the page link "648? (or the last page that you see ) in the pager.

### What's the expected result?
- Both the pagers on SWS Results page and CTS search results page should work identically.

### What's the actual result?
- The pagers are not working identically and showing more number of page links within the pager in the SWS results page than CTS search results page.

### Additional details / screenshot
- Screenshot

image

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #89 

* Update functionality of the pager to match other sites (specifically the ending sequence)

### CODE REVIEW

File: src/components/molecules/search-results-pager/search-results-pager.jsx [hunk 1]
```diff
@@ -81,14 +81,24 @@ const SearchResultsPager = ({
...
+
 		// check to see if we're less that 5 from start or end
 		const inout = start_min || current + 1 > end_total;
+
 		// set start position
 		let start = inout ? (start_min ? 1 : end_total) : current - 1;
 		let end = current > end_total ? total : current + 2;
+
 		// set decorators and end points
 		if (end >= total - 1) end = total + 1;
```
Comment (arcepaul) [inline src/components/molecules/search-results-pager/search-results-pager.jsx:93]: is this line still needed with :99 now in place?

**Comment by blilianyu** [comment]
Looks great!

**Comment by kate-mashkina** [comment]
QA is passed with a note that there is an existing issue to create integration tests for last pages of pager - while working on the tests, ODE can be tested with new changes

https://github.com/NCIOCPL/sitewide-search-app/issues/92
